#!/bin/sh

if test $# -lt 2 -o $# -gt 3; then echo "usage: $0 file.ml file.dk [proof_number]"; exit 1; fi

case "$3" in
"") range=All;;
*) range=Upto $3;;
esac
           
cat << EOF | ocaml
print_endline "------------------------------------------------------------";;
print_endline "#use \"topfind\";;";;
#use "topfind";;
print_endline "------------------------------------------------------------";;
print_endline "#require \"camlp5\";;";;
#require "camlp5";;
print_endline "------------------------------------------------------------";;
print_endline "#load \"camlp5o.cma\";;";;
#load "camlp5o.cma";;
print_endline "------------------------------------------------------------";;
print_endline "#use \"xprelude.ml\";;";;
#use "xprelude.ml";;
print_time();;
print_endline "------------------------------------------------------------";;
print_endline "#use \"$1\";;";;
#use "$1";;
print_endline "------------------------------------------------------------";;
print_endline "#use \"xlib.ml\";;";;
#use "xlib.ml";;
print_endline "------------------------------------------------------------";;
print_endline "update_map_const_type_vars_pos();;";;
update_map_const_type_vars_pos();;
print_endline "------------------------------------------------------------";;
print_endline "#use \"xlp.ml\";;";;
#use "xlp.ml";;
print_time();;
print_endline "------------------------------------------------------------";;
print_endline "export_to_lp_file \"$2\" $range;;";;
export_to_lp_file "$2" (Upto 50000);;
EOF
